<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-19T14:36:05 IST" name="Default suite" finished-at="2021-01-19T14:36:15 IST" duration-ms="10526">
    <groups>
    </groups>
    <test started-at="2021-01-19T14:36:05 IST" name="Default test" finished-at="2021-01-19T14:36:15 IST" duration-ms="10526">
      <class name="com.restassured.testcases.TC4_PutEmployeeRecord">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.restassured.testcases.TC4_PutEmployeeRecord@4470f8a6]" started-at="2021-01-19T14:36:05 IST" name="setup" finished-at="2021-01-19T14:36:05 IST" duration-ms="395" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="getsingleEmployees()[pri:0, instance:com.restassured.testcases.TC4_PutEmployeeRecord@4470f8a6]" started-at="2021-01-19T14:36:05 IST" name="getsingleEmployees" finished-at="2021-01-19T14:36:15 IST" duration-ms="9786" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getsingleEmployees -->
        <test-method signature="checkResponsebody()[pri:0, instance:com.restassured.testcases.TC4_PutEmployeeRecord@4470f8a6]" started-at="2021-01-19T14:36:15 IST" name="checkResponsebody" finished-at="2021-01-19T14:36:15 IST" duration-ms="79" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponsebody -->
        <test-method signature="checkStatusCode()[pri:0, instance:com.restassured.testcases.TC4_PutEmployeeRecord@4470f8a6]" started-at="2021-01-19T14:36:15 IST" name="checkStatusCode" finished-at="2021-01-19T14:36:15 IST" duration-ms="21" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [405]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.restassured.testcases.TC4_PutEmployeeRecord.checkStatusCode(TC4_PutEmployeeRecord.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusCode -->
        <test-method signature="contenttype()[pri:0, instance:com.restassured.testcases.TC4_PutEmployeeRecord@4470f8a6]" started-at="2021-01-19T14:36:15 IST" name="contenttype" finished-at="2021-01-19T14:36:15 IST" duration-ms="30" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contenttype -->
        <test-method is-config="true" signature="last()[pri:0, instance:com.restassured.testcases.TC4_PutEmployeeRecord@4470f8a6]" started-at="2021-01-19T14:36:15 IST" name="last" finished-at="2021-01-19T14:36:15 IST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- last -->
      </class> <!-- com.restassured.testcases.TC4_PutEmployeeRecord -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
